In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('2022-2023_bikethefts.csv', dtype={'LOR': str}, encoding='ISO-8859-1')
df.head()

,ANGELEGT_AM,TATZEIT_ANFANG_DATUM,TATZEIT_ANFANG_STUNDE,TATZEIT_ENDE_DATUM,TATZEIT_ENDE_STUNDE,LOR,SCHADENSHOEHE,VERSUCH,ART_DES_FAHRRADS,DELIKT,ERFASSUNGSGRUND
0,23.05.2023,21.05.2023,10,21.05.2023,13,01100414,1200,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
1,23.05.2023,19.05.2023,14,19.05.2023,20,02200208,650,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
2,23.05.2023,22.05.2023,19,22.05.2023,22,03701555,725,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
3,23.05.2023,22.12.2022,18,23.12.2022,9,01401044,1000,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
4,23.05.2023,22.05.2023,21,23.05.2023,7,04501043,547,Nein,Kinderfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern

In [3]:
## Convert date columns to datetime, sort by date and reset index
df['TATZEIT_ANFANG_DATUM'] = pd.to_datetime(df['TATZEIT_ANFANG_DATUM'], dayfirst=True)
df['ANGELEGT_AM'] = pd.to_datetime(df['ANGELEGT_AM'], dayfirst=True)
df['TATZEIT_ENDE_DATUM'] = pd.to_datetime(df['TATZEIT_ENDE_DATUM'], dayfirst=True)
df.sort_values('TATZEIT_ANFANG_DATUM', inplace=True, ascending=True)
df.reset_index(drop=True, inplace=True)
df

,ANGELEGT_AM,TATZEIT_ANFANG_DATUM,TATZEIT_ANFANG_STUNDE,TATZEIT_ENDE_DATUM,TATZEIT_ENDE_STUNDE,LOR,SCHADENSHOEHE,VERSUCH,ART_DES_FAHRRADS,DELIKT,ERFASSUNGSGRUND
0,2022-01-01,2022-01-01,16,2022-01-01,19,02400623,1754,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
1,2022-01-07,2022-01-01,13,2022-01-03,10,04501043,1109,Nein,diverse Fahrräder,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
2,2023-02-26,2022-01-01,0,2022-01-01,0,04501152,400,Nein,Kinderfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
3,2022-01-10,2022-01-01,12,2022-01-03,15,08100103,1093,Nein,Fahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
4,2022-04-16,2022-01-01,8,2022-01-01,8,09200613,1,Nein,Fahrrad,Fahrraddiebstahl,Einfacher Diebstahl von Fahrrädern
...,...,...,...,...,...,...,...,...,...,...,...
29786,2023-05-23,2023-05-23,2,2023-05-23,10,01300731,200,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
29787,2023-05-23,2023-05-23,6,2023-05-23,7,10200629,380,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
29788,2023-05-23,2023-05-23,6,2023-05-23,7,10200629,470,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
29789,2023-05-23,2023-05-23,7,2023-05-23,13,06300633,708,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern
29790,2023-05-23,2023-05-23,7,2023-05-23,13,02300419,388,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern

In [4]:
df['Year'] = df['TATZEIT_ANFANG_DATUM'].dt.year
df['Month'] = df['TATZEIT_ANFANG_DATUM'].dt.month
df['Day'] = df['TATZEIT_ANFANG_DATUM'].dt.day
df

,ANGELEGT_AM,TATZEIT_ANFANG_DATUM,TATZEIT_ANFANG_STUNDE,TATZEIT_ENDE_DATUM,TATZEIT_ENDE_STUNDE,LOR,SCHADENSHOEHE,VERSUCH,ART_DES_FAHRRADS,DELIKT,ERFASSUNGSGRUND,Year,Month,Day
0,2022-01-01,2022-01-01,16,2022-01-01,19,02400623,1754,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,1
1,2022-01-07,2022-01-01,13,2022-01-03,10,04501043,1109,Nein,diverse Fahrräder,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,1
2,2023-02-26,2022-01-01,0,2022-01-01,0,04501152,400,Nein,Kinderfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,1
3,2022-01-10,2022-01-01,12,2022-01-03,15,08100103,1093,Nein,Fahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,1
4,2022-04-16,2022-01-01,8,2022-01-01,8,09200613,1,Nein,Fahrrad,Fahrraddiebstahl,Einfacher Diebstahl von Fahrrädern,2022,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29786,2023-05-23,2023-05-23,2,2023-05-23,10,01300731,200,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2023,5,23
29787,2023-05-23,2023-05-23,6,2023-05-23,7,10200629,380,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2023,5,23
29788,2023-05-23,2023-05-23,6,2023-05-23,7,10200629,470,Nein,Damenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2023,5,23
29789,2023-05-23,2023-05-23,7,2023-05-23,13,06300633,708,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2023,5,23
29790,2023-05-23,2023-05-23,7,2023-05-23,13,02300419,388,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2023,5,23

In [5]:
## save preprocessed data
# df.to_csv('2022-2023_bikethefts_preprocessed.csv', index=False)

In [6]:
## get the number of bike thefts per month
df.groupby(['LOR', 'Year', 'Month']).size().reset_index(name='Bike_Thefts')

           LOR  Year  Month  Bike_Thefts
0     01100101  2022      1            1
1     01100101  2022      4            3
2     01100101  2022      5            2
3     01100101  2022      6            2
4     01100101  2022      7            1
...        ...   ...    ...          ...
6898  12601236  2022      8            1
6899  12601236  2022      9            2
6900  12601236  2022     10            1
6901  12601236  2023      3            1
6902  12601236  2023      4            1

[6903 rows x 4 columns]

In [7]:
## get the number of bike thefts per year
df.groupby(['LOR', 'Year']).size().reset_index(name='Bike_Thefts').sort_values('Year')

           LOR  Year  Bike_Thefts
0     01100101  2022           27
833   10100210  2022           21
437   05200528  2022            9
439   05200629  2022           95
831   10100209  2022           17
...        ...   ...          ...
475   06100204  2023            1
477   06100205  2023            6
479   06100206  2023            7
460   05300840  2023           11
1047  12601236  2023            2

[1048 rows x 3 columns]

In [8]:
## get certain month
df[(df['Month'] == 1) & (df['Year'] == 2022)]

,ANGELEGT_AM,TATZEIT_ANFANG_DATUM,TATZEIT_ANFANG_STUNDE,TATZEIT_ENDE_DATUM,TATZEIT_ENDE_STUNDE,LOR,SCHADENSHOEHE,VERSUCH,ART_DES_FAHRRADS,DELIKT,ERFASSUNGSGRUND,Year,Month,Day
0,2022-01-01,2022-01-01,16,2022-01-01,19,02400623,1754,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,1
1,2022-01-07,2022-01-01,13,2022-01-03,10,04501043,1109,Nein,diverse Fahrräder,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,1
2,2023-02-26,2022-01-01,0,2022-01-01,0,04501152,400,Nein,Kinderfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,1
3,2022-01-10,2022-01-01,12,2022-01-03,15,08100103,1093,Nein,Fahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,1
4,2022-04-16,2022-01-01,8,2022-01-01,8,09200613,1,Nein,Fahrrad,Fahrraddiebstahl,Einfacher Diebstahl von Fahrrädern,2022,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1233,2022-02-02,2022-01-31,15,2022-02-02,15,02200211,599,Nein,Fahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,31
1234,2022-01-31,2022-01-31,3,2022-01-31,3,04501152,300,Nein,Mountainbike,Fahrraddiebstahl,Einfacher Diebstahl von Fahrrädern,2022,1,31
1235,2022-02-08,2022-01-31,12,2022-01-31,12,08100206,300,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,31
1236,2022-01-31,2022-01-31,0,2022-01-31,9,08100209,1090,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,31
1237,2022-01-31,2022-01-31,6,2022-01-31,17,10300731,1226,Nein,Herrenfahrrad,Fahrraddiebstahl,Sonstiger schwerer Diebstahl von Fahrrädern,2022,1,31